version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/eventdb
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - JPA_DDL_AUTO=update
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=eventdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: